CREATE TABLE MEDIAN_NOISE (
  ID IDENTITY PRIMARY KEY,
  SENSOR_ID BIGINT NOT NULL,
  VALUE DECIMAL NOT NULL,
  START_TIMESTAMP TIMESTAMP NOT NULL,
  END_TIMESTAMP TIMESTAMP NOT NULL,
  CONSTRAINT FK_MEDIAN_NOISE_SENSOR_ID FOREIGN KEY(SENSOR_ID) REFERENCES SENSOR(ID)
);